# Generated by Django 4.1.7 on 2023-03-25 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={'verbose_name_plural': 'About'},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['created'], 'verbose_name_plural': 'Comment'},
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name_plural': 'Contact'},
        ),
        migrations.AlterModelOptions(
            name='contact_details',
            options={'verbose_name_plural': 'Contact_details'},
        ),
        migrations.AlterModelOptions(
            name='email',
            options={'verbose_name_plural': 'Email'},
        ),
        migrations.AlterModelOptions(
            name='ourteam',
            options={'verbose_name_plural': 'OurTeam'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-publish'], 'verbose_name_plural': 'Post'},
        ),
    ]
